apiVersion: apps/v1
kind: Deployment
metadata:
  name: oktuuy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oktuuy
  template:
    metadata:
      labels:
        app: oktuuy
    spec:
      containers:
      - image: okteto.dev/oktuuy:latest
        name: oktuuy
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "b6e96648-ffd3-4061-8fb0-4f31d283f70b"
        - name: Vless_Path
          value: "/hsgdjeiruj4"
        - name: Vmess_UUID
          value: "b6e96648-ffd3-4061-8fb0-4f31d283f70b"
        - name: Vmess_Path
          value: "/sheydufkg45"
        - name: Share_Path
          value: "/v2link"
